# Generated by Django 5.2.5 on 2025-12-09 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_routineitem_target_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsession",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
